//Informação de Estados
export const states = [
    { key: 'ACRE', label: 'ACRE' },
    { key: 'ALAGOAS', label: 'ALAGOAS' },
    { key: 'AMAPÁ', label: 'AMAPÁ' },
    { key: 'AMAZONAS', label: 'AMAZONAS' },
    { key: 'BAHIA', label: 'BAHIA' },
    { key: 'CEARÁ', label: 'CEARÁ' },
    { key: 'DISTRITO FEDERAL', label: "DISTRITO FEDERAL" },
    { key: 'ESPÍRITO SANTO', label: 'ESPÍRITO SANTO' },
    { key: 'GOIÁS', label: 'GOIÁS' },
    { key: 'MARANHÃO', label: 'MARANHÃO' },
    { key: 'MATO GROSSO', label: 'MATO GROSSO' },
    { key: 'MATO GROSSO DO SUL', label: 'MATO GROSSO DO SUL' },
    { key: 'MINAS GERAIS', label: 'MINAS GERAIS' },
    { key: 'PARÁ', label: 'PARÁ' },
    { key: 'PARAÍBA', label: 'PARAÍBA' },
    { key: 'PARANÁ', label: 'PARANÁ' },
    { key: 'PERNAMBUCO', label: 'PERNAMBUCO' },
    { key: 'PIAUÍ', label: 'PIAUÍ' },
    { key: 'RIO DE JANEIRO', label: 'RIO DE JANEIRO' },
    { key: 'RIO GRANDE DO NORTE', label: 'RIO GRANDE DO NORTE' },
    { key: 'RIO GRANDE DO SUL', label: 'RIO GRANDE DO SUL' },
    { key: 'RONDÔNIA', label: 'RONDÔNIA' },
    { key: 'RORAIMA', label: 'RORAIMA' },
    { key: 'SANTA CATARINA', label: 'SANTA CATARINA' },
    { key: 'SÃO PAULO', label: 'SÃO PAULO' },
    { key: 'SERGIPE', label: 'SERGIPE' },
    { key: 'TOCANTINS', label: 'TOCANTINS' },
]